import { z } from "zod";
import type { Prisma } from "../../generated/prisma/client.js";

// Queue data excludes beneficiary details, private object keys and policy evidence.
export const refundQueueSelect = {
  id: true,
  refundNumber: true,
  paymentAttemptId: true,
  paymentAttempt: { select: { provider: true } },
  requestedByUserId: true,
  approvedByUserId: true,
  providerRefundId: true,
  authorizationKind: true,
  policyVersionId: true,
  dueAt: true,
  clockStatus: true,
  transferredByUserId: true,
  transferRecordedAt: true,
  bankTransferAt: true,
  checkedByUserId: true,
  checkedAt: true,
  amountKobo: true,
  currency: true,
  status: true,
  reason: true,
  providerStatus: true,
  failureCode: true,
  requestedAt: true,
  approvedAt: true,
  processedAt: true,
  failedAt: true,
  updatedAt: true,
} satisfies Prisma.RefundSelect;
const date = z.iso.datetime({ offset: true }).nullable();
export const refundBeneficiarySchema = z.object({
  bankName: z.string(),
  accountName: z.string(),
  accountNumber: z.string(),
});
export const refundActionResponseSchema = z.object({
  id: z.uuid(),
  status: z.string(),
  amountKobo: z.string().regex(/^\d+$/),
  bankReference: z.string().nullable(),
  transferredAt: date,
  transferredByUserId: z.uuid().nullable(),
  checkedAt: date,
  checkedByUserId: z.uuid().nullable(),
});
export const refundEvidenceResponseSchema = z.object({
  id: z.uuid(),
  url: z.string(),
  amountKobo: z.string().regex(/^\d+$/),
  bankReference: z.string().nullable(),
  transferredAt: date,
  beneficiary: refundBeneficiarySchema.nullable(),
});
export const refundQueueRecordSchema = z.object({
  id: z.uuid(),
  refundNumber: z.string(),
  paymentAttemptId: z.uuid(),
  paymentAttempt: z.object({ provider: z.enum(["MANUAL", "PAYSTACK", "MONNIFY"]) }),
  requestedByUserId: z.uuid().nullable(),
  approvedByUserId: z.uuid().nullable(),
  providerRefundId: z.string().nullable(),
  authorizationKind: z.string(),
  policyVersionId: z.uuid().nullable(),
  dueAt: date,
  clockStatus: z.string(),
  transferredByUserId: z.uuid().nullable(),
  transferRecordedAt: date,
  bankTransferAt: date,
  checkedByUserId: z.uuid().nullable(),
  checkedAt: date,
  amountKobo: z.string().regex(/^\d+$/),
  currency: z.literal("NGN"),
  status: z.enum([
    "REQUESTED",
    "APPROVED",
    "PENDING",
    "PROCESSING",
    "NEEDS_ATTENTION",
    "SUCCEEDED",
    "FAILED",
    "CANCELLED",
  ]),
  reason: z.string(),
  providerStatus: z.string().nullable(),
  failureCode: z.string().nullable(),
  requestedAt: z.iso.datetime({ offset: true }),
  approvedAt: date,
  processedAt: date,
  failedAt: date,
  updatedAt: z.iso.datetime({ offset: true }),
});
